### ISSUE TITLE
How to get TIMIT Working

### ISSUE THREAD

**Issue by nvidiaman** [Alexander-H-Liu/End-to-end-ASR-Pytorch#12]
Hello,

I got the TIMIT data from academic torrents.

It is not working with the code.

Preprocessing training data...
Done
Preprocessing testing data...
Done
Preprocessing completed.

Collected 0 training instances from ../data/timit/train (should be 4620 in complete TIMIT )
Collected 0 testing instances from ../data/timit/test (should be 1680 in complete TIMIT )
Spliting 0 out of 0 (5.0%) training data as validation set.

Normalizing data to let mean=0, sd=1 for each channel.
[]
Traceback (most recent call last):
  File "timit_preprocess.py", line 181, in <module>
    mean_val, std_val, _ = calc_norm_param(X_train)
  File "timit_preprocess.py", line 74, in calc_norm_param
    mean_val = np.zeros(X[0].shape[1])
IndexError: list index out of range

How to make the limit example work? 

I want to upgrade the repo to python 3 as well. Could you help in giving details on how to make limit librispeech and wsj work with the las model?

**Comment by nvidiaman** [comment]
sorry for referencing this issue in other places. But any help would be very helpful, I am not sure why limit data is not working.

Also, for the Jupiter notebook there was no num_epochs in train_parameters, which requires fixing as it gives an error.Plus the magic command should be 2 words and not 3 in the Jupiter notebook.

Also, could you answer these questions:

1. How long does it take to train timit model?

2. How long does it take to train librispeech model?

3. Can wsj model be added?

**Comment by Alexander-H-Liu** [comment]
@nvidiaman 
Sorry, since this is a project I've worked on a long time ago, I've forgotten most of the details.
However, I'm recently working on the dev branch, I think I'll be able to answer all your questions (and provide config for execution) once it's done
Thank you in advance for your patience.

**Comment by Alexander-H-Liu** [comment]
@nvidiaman I've updated this project recently and now I'm able to answer your questions.

You may try the example config for TIMT now and see if it works.

(For the followings, run the example configs you cat get similar results)

>  1\. How long does it take to train timit model?

5~7 hours on single 1080Ti

>  2\. How long does it take to train librispeech model?

Depends on the training set you selected. 1 day~ 5 days on 100 hrs~960 hrs

>  3\. Can wsj model be added?

I'll try my best.

**Comment by Azura1874** [comment]
@Alexander-H-Liu Hi!
Can I please get your email? I did not see it in the description... Thanks

**Comment by nvidiaman** [comment]
thank you @Alexander-H-Liu ! 👍
