### ISSUE TITLE
Listener #layers

### ISSUE THREAD

**Issue by vinusankars** [Alexander-H-Liu/End-to-end-ASR-Pytorch#13]
Do you have any comment on using 2 encoder (listener) layers (as per your code 1 BLSTM + 1 pBLSTM) against 4 encoder layers ( 1 BLSTM + 3 pBLSTM as given in paper LAS)?

**Comment by Alexander-H-Liu** [comment]
@vinusankars I believe it depends on the corpus you're using, LAS was proposed on a large (private) corpus which allows them to use a relatively large network while my implementation focuses on the smaller (public) corpus.
