### ISSUE TITLE
AttributeError: module 'torch.nn' has no attribute 'CTCLoss'

### ISSUE THREAD

**Issue by profsatwinder** [Alexander-H-Liu/End-to-end-ASR-Pytorch#20]
I was trying to run main.py and  got following error
**AttributeError: module 'torch.nn' has no attribute 'CTCLoss'**

version details:
pytorch: 0.4.0
python 3.5.2
cuda 9.0

Could you please tell me what is causing the problem

**Comment by XiongChengxin** [comment]
Similiar error message. Any updates?
