### ISSUE TITLE
which state vector of multiple Speller layers is suggested to be used for attention calculation

### ISSUE THREAD

**Issue by XuesongYang** [Alexander-H-Liu/End-to-end-ASR-Pytorch#21]
Hi there,

I can tell from your code that you applied the state vector at the first layer of Speller to calculate attention score. 
https://github.com/Alexander-H-Liu/End-to-end-ASR-Pytorch/blob/55d39528b27b18249d1e9a084d7ac2516bfcd562/src/asr.py#L86
Did you compare it with other possible manipulations, such as 
1. The state vector at the last layer of Speller?
2. The concatenation of all state vectors from all layers?

I am interested in the advice of optimal solutions. Original LAS paper did not mention which one is the best. 

Thanks

Xuesong

**Comment by Alexander-H-Liu** [comment]
Hi,

I've never tried them but I think it's all reasonable way to implement attention and most papers/implementations (I've read so far) are using the first layer.

**Comment by XuesongYang** [comment]
Thanks man.
