### ISSUE TITLE
Multi-GPU implementation

### ISSUE THREAD

**Issue by kfmn** [Alexander-H-Liu/End-to-end-ASR-Pytorch#23]
Hi, do you plan to implement multi-GPU version of the training code?
On a single GPU even training on 100 hours Librispeech takes enormous amount of time (about 4 days for me) so the training on a whole Librispeech will take a month or more...

Maybe you can provide some instructions to do it myself? If it'll work properly I would make a pull request with corresponding changes

Thanks

**Comment by Alexander-H-Liu** [comment]
Hi @kfmn 

Sorry for the late reply, I've been busy reformatting this project.
Sadly, implementing a multi-GPU isn't in our plan, you may reference Torch's multi-gpu tutorial to implement your own version. (and you're welcomed to make contribution to this project, of course)

https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html
