### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'spm_train'

### ISSUE THREAD

**Issue by YasinZhao** [Alexander-H-Liu/End-to-end-ASR-Pytorch#25]
![image](https://user-images.githubusercontent.com/16828608/57265592-f8a7ab80-70aa-11e9-9ffe-86c560e54a78.png)

**Comment by jybaek** [comment]
install [this](https://github.com/google/sentencepiece#build-and-install-sentencepiece).

**Comment by YasinZhao** [comment]
thank you！

**Comment by Mohammadelc** [comment]
Hello, 
When I am running the same code, I got the same error. I have installed the sentencepiece package but it doesn't work. Does it work for you? or have you found anything else useful?

Mohammad

**Comment by jybaek** [comment]
If you can not use `spm_train` in a terminal, you need to make sure that the installation is working properly.
