### ISSUE TITLE
Segmentation fault (core dumped) when training on TIMIT

### ISSUE THREAD

**Issue by iamxiaoyubei** [Alexander-H-Liu/End-to-end-ASR-Pytorch#32]
Thank you for sharing the code. When I ran it on TIMIT dataset, it occurs Segmentation fault [here](https://github.com/Alexander-H-Liu/End-to-end-ASR-Pytorch/blob/55d39528b27b18249d1e9a084d7ac2516bfcd562/src/solver.py#L182). I would like to ask how to solve it.
![image](https://user-images.githubusercontent.com/21981293/62053288-e1abcc00-b249-11e9-9592-7500cdec192e.png)

**Comment by Esdsnqxz** [comment]
i have met the same status, have you solved this problem??
