### ISSUE TITLE
Is it a bug on line 88 in preprocess.py

### ISSUE THREAD

**Issue by jackaduma** [Alexander-H-Liu/End-to-end-ASR-Pytorch#43]
if mode == "word":
                    tmp.append(2)
                else:
                    tmp.append(table['<unk>'])

I think it should be 

                if mode != "word":
                    tmp.append(2)
                else:
                    tmp.append(table['<unk>'])

**Comment by Alexander-H-Liu** [comment]
Hi,

Since preprocess.py was removed after last rebase, I'm closing this issue
