### ISSUE TITLE
Multihead attention

### ISSUE THREAD

**Issue by d223302** [Alexander-H-Liu/End-to-end-ASR-Pytorch#44]
I think there is an no attribute error in /src/asr.py line 437 : self.preprocess_mlp_dim. Should it be self.num_head? Thanks for your great and clear implementation.

**Comment by Alexander-H-Liu** [comment]
Hi @d223302 ,

You're right, multi-head attention implementation wasn't correct in the last version,
We've update our code recently, I believe it's correct now. 
If you're interested, please have a look at [line 138-235 in src/module.py](https://github.com/Alexander-H-Liu/End-to-end-ASR-Pytorch/blob/a8ded12509d5ad1b8a0e66c89640b7cb5231828e/src/module.py#L138-L235)

Thanks a lot for appreciating our work!
