### ISSUE TITLE
Error in CharacterTextEncoder 

### ISSUE THREAD

**Issue by gheyret** [Alexander-H-Liu/End-to-end-ASR-Pytorch#51]
Hi,
In decode method in CharacterTextEncoder have error.
Line 65:
if idx == self.pad_idx or (ignore_repeat and t > 0 and idx == **vocabs**[t-1]):

I think must be:
if idx == self.pad_idx or (ignore_repeat and t > 0 and idx == **idxs**[t-1]):

**Comment by Alexander-H-Liu** [comment]
Hi @gheyret ,

You're right, thanks for identifying the question
fixed in fa6683b60b57d1dc8fc27d16885f583752745d67
