### ISSUE TITLE
Facing missing positional argument : 'init_adadelta'

### ISSUE THREAD

**Issue by shamil-kadavan** [Alexander-H-Liu/End-to-end-ASR-Pytorch#53]
While testing the model on 'test-clean' dataset, i am facing issue 
"self.model = ASR(self.feat_dim, self.vocab_size, **self.config['model'])", this error is occurring because it is missing one required positional argument : 'inint_adadelta'
![image](https://user-images.githubusercontent.com/59653662/73427243-575d3580-435c-11ea-822d-d2e0ca81ae3f.png)

i only changed the max_steps, tf_steps and valid_step in asr_example.yaml config file

**Comment by shamil-kadavan** [comment]
Hi Team,
the test_asr.py file needs some addition
"
        init_adadelta = self.config['hparas']['optimizer'] == 'Adadelta'

        self.model = ASR(self.feat_dim, self.vocab_size,init_adadelta, **self.config['model'])
"
This should be added in set_model in class Solver

**Comment by Alexander-H-Liu** [comment]
Hi @shamil-kadavan 

you're right, we forgot to add this part in testing since the last update
fixed in fa6683b60b57d1dc8fc27d16885f583752745d67
thanks

**Comment by shamil-kadavan** [comment]
Hi @Alexander-H-Liu ,
i am new to this Speech Recognition field. Can you help me with single file inference problem.
